### ISSUE TITLE
"Cache to library" not working - Failed to move

### ISSUE THREAD

**Issue by jneuhauser** [toniebox-reverse-engineering/teddycloud#142]
Hello @SciLor ,

many thanks for your last update of teddycloud.

Sadly I have to report a non working "Cache to library" feature.

Here is the log output for a new original tonie content download:
```
teddycloud  | INFO |server.c:0253:httpServerRequestCallback| UA=toniebox-esp32-eu/v5.230.0, ESPFW=eu/v5.230.0
teddycloud  | INFO |handler_cloud.c:0316:handleCloudContent|  >> client requested content for rUID 54640415500304e0, auth D7933CDA...
teddycloud  | INFO |handler_cloud.c:0520:handleCloudContent| Serve cloud content from /v2/content/54640415500304e0
teddycloud  | INFO |cloud_request.c:0161:web_request| Connecting to HTTP server prod.de.tbs.toys:443...
teddycloud  | INFO |cloud_request.c:0211:web_request|   trying IP: 3.74.99.150
teddycloud  | INFO |cloud_request.c:0038:httpClientTlsInitCallbackBase| Initializing TLS...
teddycloud  | INFO |cloud_request.c:0073:httpClientTlsInitCallbackBase| Initializing TLS done
teddycloud  | INFO |cloud_request.c:0311:web_request| HTTP code: 200
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Server = openresty
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Date = Mon, 25 Mar 2024 22:59:31 GMT
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Content-Type = binary/octet-stream
teddycloud  | INFO |cloud_request.c:0374:web_request| Content-Type is binary/octet-stream
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Content-Length = 32405814
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Connection = keep-alive
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Last-Modified = Wed, 16 Jun 2021 11:57:22 GMT
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: ETag = "24c89a978998f3d18ab82e1a99c0b43d-4"
teddycloud  | INFO |handler.c:0068:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: Accept-Ranges = bytes
teddycloud  | INFO |handler.c:0074:cbrCloudHeaderPassthrough| >> cbrCloudHeaderPassthrough: NULL
teddycloud  | INFO |cloud_request.c:0395:web_request| Binary data, not dumping body
teddycloud  | INFO |handler.c:0112:cbrCloudBodyPassthrough| >> Start caching uri=/v2/content/54640415500304e0
teddycloud  | INFO |handler.c:0149:cbrCloudBodyPassthrough| >> Successfully cached /teddycloud/data/content/default/54640415/500304E0
teddycloud  | ERROR|handler.c:0200:cbrCloudBodyPassthrough| >> Failed to move /teddycloud/data/content/default/54640415/500304E0 to library /teddycloud/data/library/by/audioID/1623844621.taf
teddycloud  | INFO |handler.c:0304:cbrCloudServerDiscoPassthrough| >> cbrCloudServerDiscoPassthrough
teddycloud  | INFO |cloud_request.c:0452:web_request| Connection closed
```

My used `docker-compose.yaml` looks like:
```
version: '3'
services:
  teddycloud:
    container_name: teddycloud
    hostname: teddycloud
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:latest
    ports:
      - 80:80 #optional
      - 443:443 #Port is needed for the connection for the box
    volumes:
      - certs:/teddycloud/certs
      - config:/teddycloud/config
      - content:/teddycloud/data/content
      - library:/teddycloud/data/library
      - firmware:/teddycloud/data/firmware
    restart: unless-stopped
volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: /mnt/teddycloud/certs
      o: bind
  config:
    driver: local
    driver_opts:
      type: none
      device: /mnt/teddycloud/config
      o: bind
  content:
    driver: local
    driver_opts:
      type: none
      device: /mnt/teddycloud/data/content
      o: bind
  library:
    driver: local
    driver_opts:
      type: none
      device: /mnt/teddycloud/data/library
      o: bind
  firmware:
    driver: local
    driver_opts:
      type: none
      device: /mnt/teddycloud/data/firmware
      o: bind
```

The folder `/teddycloud/data/library/by/audioID/` gets created successfully, but moving seems to fail.

Do you have any clue why moving from `content` to `library` fails?
