### ISSUE TITLE
Documentation unclear ?

### ISSUE THREAD

**Issue by Nesego** [toniebox-reverse-engineering/teddycloud#92]
Hi ! I'm trying to setup the docker container, and got stuck with the same issue as in #84  . Except I don't get where I'm supposed to start. I'm guessing that `flash:/cert/ca.der (Boxine CA), flash:/cert/client.der (Client Cert) and flash:/cert/private.der (Client private key).` [mentioned in the wiki](https://toniebox-reverse-engineering.github.io/docs/tools/teddycloud/#:~:text=run%20without%20the-,flash%3A/cert/ca.der%20(Boxine%20CA)%2C%20flash%3A/cert/client.der%20(Client%20Cert)%20and%20flash%3A/cert/private.der%20(Client%20private%20key).,-An%20example%20docker) are the originals, that need to be extracted from the box.

But the doc says that this should be done with teddyBench, which [wiki page is empty](https://toniebox-reverse-engineering.github.io/docs/tools/teddybench/) and name doesn't match a repo here. So what are the correct steps ? Even when reading [the main page](https://toniebox-reverse-engineering.github.io/docs/tools/teddycloud/) of Features and Preparations I don't get what I'm supposed to do first, this is very confusing.

(Also, I configured the teddycloud to run on a personalized port (9999) because I'm running this on a VPS where port 80 is already occupied, hope that's okay. By the way, the link to the example YAML at the bottom is also dead, got it from the repo, [here](https://github.com/toniebox-reverse-engineering/teddycloud/blob/master/docker/docker-compose.yaml) )

**My YAML :**
```
teddycloud:
    container_name: teddycloud
    hostname: teddycloud
    image: ghcr.io/toniebox-reverse-engineering/teddycloud:latest
    ports:
      - 9999:9999 #optional
      - 443:443 #Port is needed for the connection for the box
    volumes:
      - /home/ubuntu/raspi-docker/teddycloud/certs:/teddycloud/certs
      - /home/ubuntu/raspi-docker/teddycloud/config:/teddycloud/config
      - /home/ubuntu/raspi-docker/teddycloud/content:/teddycloud/data/content
      - /home/ubuntu/raspi-docker/teddycloud/library:/teddycloud/data/library
      - /home/ubuntu/raspi-docker/teddycloud/firmware:/teddycloud/data/firmware
    restart: unless-stopped
```
